# Generated by Django 4.2.3 on 2023-08-12 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=402)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.album')),
            ],
        ),
    ]
