# Generated by Django 4.2.3 on 2023-07-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barer_shop', '0002_rename_location_contact_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='branche',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
