# Generated by Django 4.2.3 on 2023-07-21 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Barer_shop', '0005_contact_branch3_contact_branche2_contact_locatio3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='branch3',
            new_name='branche3',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='locatio3',
            new_name='location3',
        ),
    ]
