# Generated by Django 4.2.3 on 2023-07-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barer_shop', '0006_rename_branch3_contact_branche3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branche', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
