# Generated by Django 4.2.3 on 2023-07-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barer_shop', '0008_branches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Branches',
        ),
        migrations.DeleteModel(
            name='Footer',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='branche',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='branche2',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='branche3',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='location',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='location2',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='location3',
        ),
    ]
