# Generated by Django 4.2.3 on 2023-07-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=402)),
                ('location', models.CharField(max_length=402)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=402)),
                ('email', models.CharField(max_length=402)),
                ('time', models.CharField(max_length=402)),
                ('link', models.CharField(max_length=402)),
            ],
        ),
    ]
